### ISSUE TITLE
在compose 1.4.3的版本报错

### ISSUE THREAD

**Issue by shenyunhuan** [huhx/compose_image_picker#24]
Process: com.gtrides.passenger, PID: 28742
                 java.lang.ClassCastException: androidx.compose.animation.AnimatedContentTransitionScopeImpl cannot be cast to androidx.compose.animation.AnimatedContentScope
                 	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$7$1.invoke(AnimatedNavHost.kt:198)
                 	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:787)
                 	at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:196)
                 	at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:89)
                 	at com.huhx.picker.data.AssetRouteKt.AssetPickerRoute(AssetRoute.kt:23)
                 	at com.huhx.picker.view.AssetPickerKt$AssetPicker$2.invoke(AssetPicker.kt:38)
                 	at com.huhx.picker.view.AssetPickerKt$AssetPicker$2.invoke(AssetPicker.kt:37)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at com.huhx.picker.view.AssetPickerKt.AssetPicker(AssetPicker.kt:37)

**Comment by pradyotprksh** [comment]
getting the same error for `io.github.huhx:compose-image-picker:1.0.8`
